spring.application.name=RoomMatcher
logging.level.org.springframework.web=DEBUG

jwt.token-validity-seconds=86400
jwt.refresh-token-validity-seconds=604800
jwt.base64-secret=nekiBase64SecretOdMinimalno32Znaka
